### ISSUE TITLE
[BUG] Issue Title

### ISSUE THREAD

**Issue by IBitePancakes** [CathieNova/Haven-VCQL-Helper#1]
**Description**
Pressing on generate quest json doesnt work

**Steps to Reproduce**
Just create a random quest

**Expected Behavior**
Its expected to create a quest.json

**Screenshots**
N/A

**Comment by CathieNova** [comment]
It's not supposed to create a quest.json, it will generate this at the bottom:
![Screenshot](https://github.com/user-attachments/assets/d5d9f861-cbaa-44d0-a152-3c464db46515)

**Comment by IBitePancakes** [comment]
Well in such case I cant see the output
![image](https://github.com/user-attachments/assets/26112017-0c78-4f6d-931d-f36138cad71d)

**Comment by CathieNova** [comment]
Can you inspect the page and look at console and see if there's any Red text? (errors)

**Comment by IBitePancakes** [comment]
![image](https://github.com/user-attachments/assets/c539e17e-f660-4ddf-a18f-c7b315d612f8)
This is the error in question

**Comment by CathieNova** [comment]
Refresh page and try again, it should be fixed.

**Comment by IBitePancakes** [comment]
Yup I gotta recreate the quest now.

**Comment by IBitePancakes** [comment]
Well It doesnt work all of a sudden when I fill in the gaps, Is there something im doing wrong

**Comment by CathieNova** [comment]
What browser are you using?

**Comment by IBitePancakes** [comment]
Google

**Comment by CathieNova** [comment]
It works for me in Chrome, can you tell me what you're trying to fill in? perhaps screenshot it if it's not too much trouble

**Comment by IBitePancakes** [comment]
![image](https://github.com/user-attachments/assets/98ec9f4e-0113-41b9-a270-7479c3edd28c)
![image](https://github.com/user-attachments/assets/3fbbf8ff-8880-4ca6-bcb5-f9b16859d5f3)

**Comment by CathieNova** [comment]
It should be fixed now, i fixed an error in the last spot, i have also tested all fields and they should generate the json now, i'm sorry i forgot that last one.

**Comment by IBitePancakes** [comment]
Seems to be working I got to go run some errands Ill report back later if theres any other errors

**Comment by CathieNova** [comment]
Sounds good, i'll leave the issue open for the time being ^_^

**Comment by IBitePancakes** [comment]
Is quest assortments meant to be empty?
![image](https://github.com/user-attachments/assets/25f6221e-7004-40f9-bd68-e70be2a8c3f9)
everything else seems to work

**Comment by CathieNova** [comment]
If you didnt add any assortments then it should be empty yes, but i should probably make it not show up if no assortmentunlocks has been added

**Comment by CathieNova** [comment]
Fixed so the AssortmentUnlocks only show up if there are any.
And with that i'm closing the issue since everything seems to be in order ^_^
I really appreciate you reporting issues so they can be fixed ❤️
