### ISSUE TITLE
[BUG] invalid value in sideExclusive/side

### ISSUE THREAD

**Issue by Frosht** [CathieNova/Haven-VCQL-Helper#2]
**Description**
When creating a quest, it populates the value "side" with "any".
This breaks the quest, and makes the EFT client stuck on loading, SPT server console stops at "[Client Request] /client/quest/list"

**Steps to Reproduce**
1. Create a quest (seems to happen with any variant of quest I tried) 

**Expected Behavior**
To populate with a valid value (I believe it's Pmc, Bear or Usec)

**Browser**
Firefox

Suggestion on solution here is to either change the "any" value to "Pmc", or add a dropdown.

**Comment by CathieNova** [comment]
I will look into it when i'm better as i've been to the hospital for 4 days.

**Comment by CathieNova** [comment]
This is now fixed, should work in the next few minutes after you refresh.
