### ISSUE TITLE
[BUG] Objective ID in quest JSON doesn't match with Languge or objective ID in the helper

### ISSUE THREAD

**Issue by Frosht** [CathieNova/Haven-VCQL-Helper#3]
**Description**
In the Quest JSON, the value might be:
672a896af71132bbb48f9190 

However in GUI and Quest language JSON, the value is:
672a87736e658f754fb54cad 

This results that the game instead presents the ID instead of the text.

Example would be, I create a handover quest for milk, and I put in "Hand in 2 milk cartons". 
In the game, this would instead present "672a896af71132bbb48f9190", instead of the text above.

**Steps to Reproduce**
Create a quest (seems to happen with any variant of quest I tried)

**Expected Behavior**
That the ID's match, so the game can present the correct task description

**Browser**
Firefox

**Comment by CathieNova** [comment]
I will look into it when i'm better as i've been to the hospital for 4 days.

**Comment by CathieNova** [comment]
Did you write in the objectives lang field for that quest?
![firefox_y0qIZMLGH3](https://github.com/user-attachments/assets/25b71e77-536e-423e-8bbf-b32743a15795)

so it looks like this:
![firefox_N4bppvHWrb](https://github.com/user-attachments/assets/cace7d58-95cb-4da7-9cc3-ed0dea7c485a)

**Comment by Frosht** [comment]
Yep.
And in the quest json file, that ID isn't used.
So instead of the objective 1 text being shown in game, you see the actual objective ID instead.

I don't have a pc available for about a day, so not able to test, but I believe that the ID in picture under is what's presented instead. 

![Screenshot_20241109_131446_Firefox](https://github.com/user-attachments/assets/849a33af-52d8-48df-a09f-d0cb8f71cd0f)

Replacing that ID with the one created in the language json makes it work properly.

Hopefully that made sense.
hope you're feeling better.

**Comment by CathieNova** [comment]
I believe i managed to fix it all properly now, i'll leave this issue open for today and close it if i don't hear anything ^_^

Yes i do feel better thank you!

**Comment by Frosht** [comment]
Looks good now, not tested but I'll get back to you tomorrow if it doesn't work :)
have a good rest of your weekend.

**Comment by CathieNova** [comment]
Should now be fixed.

**Comment by Frosht** [comment]
Yea sorry, I never got around to testing it. Glad to hear it's fixed :)
