### ISSUE TITLE
[BUG] Location conditions cannot be linked to main condition types

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-VCQL-Helper#4]
**Description**
Creating a quest with any condition cannot be successfully linked to a location. If a quest has specific requirements per location, the tasks can be uniquely separated. E.g. kill 5 on wood, kill 10 on reserve, kill 15 on interchange. Additionally, this create objective description bloat in the "Quest Language Variables" section that does not need to exist

**Steps to Reproduce**
1. Set an objective, exit status or any condition type
3. Select the location condition and any location

**Expected Behavior**
Example given from Shooter Born in Heaven, Woods kill condition. Location is embedded within the condition set:
      {
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [
                  "Head"
                ],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 0,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 0
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "5c0bdf4286f77454f5264f06",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "AnyPmc",
                "value": 1,
                "weapon": [
                  "627e14b21713922ded6f2c15",
                  "5ae08f0a5acfc408fb1398a1",
                  "55801eed4bdc2d89578b4588",
                  "588892092459774ac91d4b11",
                  "5df24cf80dee1b22f862e9bc",
                  "5bfea6e90db834001b7347f3",
                  "61f7c9e189e6fb1a5e3ea78d",
                  "5bfd297f0db834001a669119",
                  "5de652c31b7e3716273428be"
                ],
                "weaponCaliber": [],
                "weaponModsExclusive": [],
                "weaponModsInclusive": []
              },
              {
                "conditionType": "Location",
                "dynamicLocale": false,
                "id": "5c0be31986f774467a116592",
                "target": [
                  "Woods"
                ]
              }
            ],
            "id": "5c0bdf2c86f7746f016734a7"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "5c0bdf2c86f7746f016734a8",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Elimination",
          "value": 5,
          "visibilityConditions": []
        },

Another example of expected results from Sales Night:
{
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "conditionType": "Location",
                "dynamicLocale": false,
                "id": "5ae9e46686f77440d37ce046",
                "target": [
                  "Interchange"
                ]
              },
              {
                "conditionType": "ExitStatus",
                "dynamicLocale": false,
                "id": "5bb60cc688a4507f2f385a76",
                "status": [
                  "Survived"
                ]
              }
            ],
            "id": "5ae9e44f86f7746b6a466a8d"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "5bb60cbc88a45011a8235cc5",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Completion",
          "value": 7,
          "visibilityConditions": []
        }

Expected result on my custom quest, Right in the Dome. Quest location has been manually imbedded into condition requirements:
        {
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [
                  ""
                ],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 0,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 220
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "6736cc84161f89b4390cbf37",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "Any",
                "value": 10,
                "weapon": [],
                "weaponCaliber": [
                  "all"
                ],
                "weaponModsExclusive": [],
                "weaponModsInclusive": []
              },
			  {
          "conditionType": "Location",
          "dynamicLocale": false,
          "id": "6736b2ced76df5e026ee3bbf",
          "target": [
            "RezervBase"
          ],
          "visibilityConditions": []
			}
            ],
            "id": "6736cc848355f0da7bcefa46"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "6736b15d539c20423ee1b344",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Elimination",
          "value": 10,
          "visibilityConditions": []
        }

Actual Result on my custom quest, Right in the Dome. Location is not embedded and a separate condition:

{
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [
                  ""
                ],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 220,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 220
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "6737e7be427acbc9a6588b70",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "Any",
                "value": 10,
                "weapon": [],
                "weaponCaliber": [
                  "all"
                ],
                "weaponModsInclusive": [],
                "weaponModsExclusive": []
              }
            ],
            "id": "6737e7beaf33a6e44f8073ce"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "6737e7beaf2814625f75006b",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Elimination",
          "value": 10,
          "visibilityConditions": []
        },
        {
          "conditionType": "Location",
          "dynamicLocale": false,
          "id": "6737e7b30456e227d6622128",
          "index": 1,
          "target": [
            "RezervBase"
          ],
          "visibilityConditions": []
        }

**Browser**
Chrome

**Comment by CathieNova** [comment]
I noticed i messed up the kill location condition which was fixed yesterday (tested and confirmed)

**Comment by Gholdin** [comment]
Will do, thanks for fixing it :)

**Comment by CathieNova** [comment]
Fixed the "ExitStatus" to have a subcondition just like the kills ^_^

**Comment by Gholdin** [comment]
Awesome!
