### ISSUE TITLE
[FEATURE] Place Beacon

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-VCQL-Helper#5]
**Description**
Please add the condition type, "place beacon" into the objective types selection. This would allow quest creators to use the animations set in game to actively throw beacons on walls, floors, objects, etc. This would apply for jammers, ms2000s, and radio repeaters. 

**Proposed Solution**
Use the following condition type block to implement:
{
          "conditionType": "PlaceBeacon",
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "5b478d8986f774563c7a4809",
          "index": 0,
          "parentId": "",
          "plantTime": 30,
          "target": [
            "5991b51486f77447b112d44f"
          ],
          "value": 1,
          "visibilityConditions": [],
          "zoneId": "place_merch_21_1"
        }

**Additional Context**
See network provider part 2, or stead signal quests for examples.

**Comment by CathieNova** [comment]
I have not tested it, i've only followed what's written [here:](https://hub.sp-tarkov.com/doc/entry/57-resources-quest-values-reference-tool/)

If you have tested it and it works i'll gladly add it, but as written in the url above these are the only supported condition types:
- PickUp
- Exploration
- Skill
- Discover
- Completion
- Elimination
- WeaponAssembly
- Multi
- Merchant
- Loyalty

**Comment by Gholdin** [comment]
Hello, the code I copied was straight from the BSG's quest "Minibus". I haven't tested it myself, but the code is there and should work as it's the same implement as BSG's code for beacon placing quests. I'm assuming a lot here since I'm still writing out my quests using your helper tool. I'll test it here soon and report back what I find.

**Comment by Gholdin** [comment]
Back. The code works. Just waiting on you to put it in :)

**Comment by CathieNova** [comment]
Added the "PlaceBeacon" Condition, it generates just like EFT's method, but i have not tested it ^_^

**Comment by Gholdin** [comment]
Nice, thank you!
