### ISSUE TITLE
[FEATURE] Counter condition for Exit status objective conditions

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-VCQL-Helper#6]
**Description**
Add a 'countercreator' condition type to the existing exit status condition type by default. The default value can be left at one, but this will allow quest creators to add extraction quantities similar to already existing BSG quests. Example: Success criteria: Extract from woods 7 times.  Fail criteria: MIA from woods 3 times.

**Proposed Solution**
As demonstrated by the quest, Sales Night, where the player must extract from Interchange 7 times. The exit status condition types share the similar 'countercreator' condition type parameters to 'kill' condition types:
`      "AvailableForFinish": [
        {
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "conditionType": "Location",
                "dynamicLocale": false,
                "id": "5ae9e46686f77440d37ce046",
                "target": [
                  "Interchange"
                ]
              },
              {
                "conditionType": "ExitStatus",
                "dynamicLocale": false,
                "id": "5bb60cc688a4507f2f385a76",
                "status": [
                  "Survived"
                ]
              }
            ],
            "id": "5ae9e44f86f7746b6a466a8d"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "5bb60cbc88a45011a8235cc5",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Completion",
          "value": 7,
          "visibilityConditions": []
        }
      ],`

**Comment by CathieNova** [comment]
Added and should work.

**Comment by Gholdin** [comment]
Looks great, thank you!

**Comment by MTeyCFA** [comment]
I believe this is still an issue. On the website I've made it so the PMC has to survive until the quest objective is completed, however, the output code doesn't work as intended. Just as the @Gholdin mentioned, there should be a default CounterCreator before all the extra options.

For the quest failure state the website outputs this:
![image](https://github.com/user-attachments/assets/4d5bd8c3-bd34-42d2-990a-614c8d90da76)

The working code looks like this:
![image](https://github.com/user-attachments/assets/ff1bf863-8535-4d26-8b43-68ee635726cd)

The added locations are mine just to be safe, cause BSG code is whack, although either omitting it or
```
"target": [
   "any"
]
```
might work too.

**Comment by CathieNova** [comment]
If you're using both ExitStatus and Location you should use this:
![opera_NW1t15SqyS](https://github.com/user-attachments/assets/00e8d15c-17eb-486b-978b-a94d801203da)
