### ISSUE TITLE
[BUG] Equipment conditions cannot be linked to main condition types

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-VCQL-Helper#7]
**Description**
Equipment conditions does not exist as a sub-condition attached to main condition types, like 'kill' type conditions, but may be attached to other objective conditions. 

**Steps to Reproduce**
1. Select quest objective
2. Select a equipment objective

**Expected Behavior**
As shown in the quest, Peacekeeping mission, where the player must wear a UNTAR helmet, UNTAR Armor and an M4A1 assault rifle. The equipment objective condition is embedded into the 'kill' objective condition.
`{
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 0,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 0
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "5c0d4c6ed0928202a62f4f20",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "Savage",
                "value": 1,
                "weapon": [
                  "5447a9cd4bdc2dbd208b4567"
                ],
                "weaponCaliber": [],
                "weaponModsExclusive": [],
                "weaponModsInclusive": []
              },
              {
                "IncludeNotEquippedItems": false,
                "conditionType": "Equipment",
                "dynamicLocale": false,
                "equipmentExclusive": [],
                "equipmentInclusive": [
                  [
                    "5aa7d03ae5b5b00016327db5",
                    "5ab8e4ed86f7742d8e50c7fa"
                  ]
                ],
                "id": "5c0d4c88d09282029f539179"
              },
              {
                "conditionType": "Location",
                "dynamicLocale": false,
                "id": "5c0d4cf2d0928202b25db712",
                "target": [
                  "Woods"
                ]
              }
            ],
            "id": "5c0d4c62d09282029d76ad28"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "5c1fd66286f7743c7b261f7b",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Elimination",
          "value": 12,
          "visibilityConditions": []
        }`

**Actual Behavior**
A custom generated quest through the VCQL helper tool. The equipment condition is separated from the "kill" condition and thus not required to complete the kills in the quest.
`{
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [
                  ""
                ],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 0,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 0
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "67390ed7daca47ac33b9c9ec",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "Any",
                "value": 25,
                "weapon": [],
                "weaponCaliber": [
                  "all"
                ],
                "weaponModsInclusive": [],
                "weaponModsExclusive": []
              },
              {
                "conditionType": "Location",
                "dynamicLocale": false,
                "id": "67390ed7cd16be2e85718c68",
                "target": [
                  "laboratory"
                ]
              }
            ],
            "id": "67390ed783d791f5af7568de"
          },
          "doNotResetIfCounterCompleted": false,
          "dynamicLocale": false,
          "globalQuestCounterId": "",
          "id": "67390ed7c499d400e77eb588",
          "index": 0,
          "oneSessionOnly": false,
          "parentId": "",
          "type": "Elimination",
          "value": 25,
          "visibilityConditions": []
        },
        {
          "includeNotEquippedItems": false,
          "conditionType": "Equipment",
          "index": 1,
          "dynamicLocale": false,
          "equipmentExclusive": [],
          "equipmentInclusive": [
            "5ab8e4ed86f7742d8e50c7fa"
          ],
          "id": "67390eb2ccc0f64d19d6f9f6",
          "visibilityConditions": []
        }`

**Browser**
Chrome

**Comment by CathieNova** [comment]
Added, should work just like Peacekeeping mission, i also added it to the Fail Condition too.

**Comment by Gholdin** [comment]
It works! Thank you. I haven't tested the failure condition type to see how it behaves, so I won't be able to answer that one
